title: Shahed Sufian
logo: assets/Shahed Sufian profile photo-resized.jpg
description: Health Systems, Services, and Policy Research Scientist | Data Scientist | Public Health Expert | Digital Health Professional
show_downloads: true
theme: jekyll-theme-minimal
